// <auto-generated />
using System;
using Certitrack;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Certitrack.Migrations
{
    [DbContext(typeof(CertitrackContext))]
    partial class CertitrackContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Certitrack.Certificate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("CertificateNo")
                        .HasColumnName("certificate_no")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<DateTime>("DateIssued")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("DATE_issued")
                        .HasColumnType("date")
                        .HasDefaultValueSql("(CONVERT([date],getdate()))");

                    b.Property<DateTime?>("DateRedeemed")
                        .HasColumnName("DATE_redeemed")
                        .HasColumnType("date");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnName("expiry_DATE")
                        .HasColumnType("date");

                    b.Property<decimal>("Price")
                        .HasColumnName("price")
                        .HasColumnType("decimal(18, 0)");

                    b.HasKey("Id");

                    b.ToTable("certificate");
                });

            modelBuilder.Entity("Certitrack.CertificateLink", b =>
                {
                    b.Property<int>("CertificateId")
                        .HasColumnName("certificate_id");

                    b.Property<int?>("ChannelId")
                        .HasColumnName("channel_id");

                    b.Property<int?>("CustomerId")
                        .HasColumnName("customer_id");

                    b.Property<int?>("PromotionId")
                        .HasColumnName("promotion_id");

                    b.Property<int?>("StaffId")
                        .HasColumnName("staff_id");

                    b.HasKey("CertificateId");

                    b.HasIndex("ChannelId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PromotionId");

                    b.HasIndex("StaffId");

                    b.ToTable("certificate_link");
                });

            modelBuilder.Entity("Certitrack.Channel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Channel1")
                        .IsRequired()
                        .HasColumnName("channel")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("channel");
                });

            modelBuilder.Entity("Certitrack.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnName("email")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnName("phone")
                        .HasMaxLength(15)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("customer");
                });

            modelBuilder.Entity("Certitrack.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CustomerId")
                        .HasColumnName("customer_id");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("order");
                });

            modelBuilder.Entity("Certitrack.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CertificateId")
                        .HasColumnName("certificate_id");

                    b.Property<int>("OrderId")
                        .HasColumnName("order_id");

                    b.HasKey("Id");

                    b.HasIndex("CertificateId");

                    b.HasIndex("OrderId");

                    b.ToTable("order_item");
                });

            modelBuilder.Entity("Certitrack.Promotion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Discount")
                        .HasColumnName("discount");

                    b.HasKey("Id");

                    b.ToTable("promotion");
                });

            modelBuilder.Entity("Certitrack.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnName("description")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnName("title")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("role");
                });

            modelBuilder.Entity("Certitrack.Staff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("created")
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnName("email")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnName("password")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("staff");
                });

            modelBuilder.Entity("Certitrack.StaffLink", b =>
                {
                    b.Property<int>("StaffId")
                        .HasColumnName("staff_id");

                    b.Property<int>("RoleId")
                        .HasColumnName("role_id");

                    b.Property<int>("StaffTypeId")
                        .HasColumnName("staff_type_id");

                    b.HasKey("StaffId");

                    b.HasIndex("RoleId");

                    b.HasIndex("StaffTypeId");

                    b.ToTable("staff_link");
                });

            modelBuilder.Entity("Certitrack.StaffType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnName("type")
                        .HasMaxLength(45)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("staff_type");
                });

            modelBuilder.Entity("Certitrack.CertificateLink", b =>
                {
                    b.HasOne("Certitrack.Certificate", "Certificate")
                        .WithOne("CertificateLink")
                        .HasForeignKey("Certitrack.CertificateLink", "CertificateId")
                        .HasConstraintName("FK_certificate_cLink");

                    b.HasOne("Certitrack.Channel", "Channel")
                        .WithMany("CertificateLink")
                        .HasForeignKey("ChannelId")
                        .HasConstraintName("FK_channel_cLink")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Certitrack.Customer", "Customer")
                        .WithMany("CertificateLink")
                        .HasForeignKey("CustomerId")
                        .HasConstraintName("FK_customer_cLink");

                    b.HasOne("Certitrack.Promotion", "Promotion")
                        .WithMany("CertificateLink")
                        .HasForeignKey("PromotionId")
                        .HasConstraintName("FK_promotion_cLink");

                    b.HasOne("Certitrack.Staff", "Staff")
                        .WithMany("CertificateLink")
                        .HasForeignKey("StaffId")
                        .HasConstraintName("FK_staff_cLink");
                });

            modelBuilder.Entity("Certitrack.Order", b =>
                {
                    b.HasOne("Certitrack.Customer", "Customer")
                        .WithMany("Order")
                        .HasForeignKey("CustomerId")
                        .HasConstraintName("FK_customer_order")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Certitrack.OrderItem", b =>
                {
                    b.HasOne("Certitrack.Certificate", "Certificate")
                        .WithMany("OrderItem")
                        .HasForeignKey("CertificateId")
                        .HasConstraintName("FK_certificate_oItem")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Certitrack.Order", "Order")
                        .WithMany("OrderItem")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("FK_order_oItem");
                });

            modelBuilder.Entity("Certitrack.StaffLink", b =>
                {
                    b.HasOne("Certitrack.Role", "Role")
                        .WithMany("StaffLink")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("FK_role_sLink");

                    b.HasOne("Certitrack.Staff", "Staff")
                        .WithOne("StaffLink")
                        .HasForeignKey("Certitrack.StaffLink", "StaffId")
                        .HasConstraintName("FK_staff_sLink");

                    b.HasOne("Certitrack.StaffType", "StaffType")
                        .WithMany("StaffLink")
                        .HasForeignKey("StaffTypeId")
                        .HasConstraintName("FK_staff_type_sLink")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
